use super::{backup_before_write, HookAdapter};
use std::path::{Path, PathBuf};

pub struct OpencodeAdapter;

const MARKER: &str = "// generated by harness-notify, do not edit by hand";

fn plugin_path(base_dir: &Path) -> PathBuf {
    base_dir.join("plugin").join("harness-notify.js")
}

fn plugin_source(binary_path: &Path) -> String {
    let bin = serde_json::to_string(&binary_path.display().to_string())
        .expect("string serialization is infallible");
    format!(
        r#"{marker}
export default async ({{ directory }}) => {{
  const {{ spawn }} = await import("node:child_process")
  const fire = (event, cwd) => {{
    const args = ["notify", "--harness", "opencode", "--event", event]
    if (cwd) args.push("--cwd", cwd)
    spawn({bin}, args, {{ stdio: "ignore", detached: true }}).unref()
  }}
  const check = () => {{
    spawn({bin}, ["check", "--hook", "session-created"], {{ stdio: "ignore", detached: true }}).unref()
  }}

  let doneTimer = null
  const DONE_DEBOUNCE_MS = 15_000

  return {{
    event: async ({{ event }}) => {{
      if (event.type === "permission.asked") {{
        clearTimeout(doneTimer)
        doneTimer = null
        fire("attention")
      }}
      if (event.type === "session.idle") {{
        clearTimeout(doneTimer)
        doneTimer = setTimeout(() => {{ doneTimer = null; fire("done", directory) }}, DONE_DEBOUNCE_MS)
      }}
      if (event.type === "session.created") check()
    }},
  }}
}}
"#,
        marker = MARKER,
        bin = bin,
    )
}

impl HookAdapter for OpencodeAdapter {
    fn id(&self) -> &'static str {
        "opencode"
    }

    fn install(&self, base_dir: &Path, binary_path: &Path) -> Result<(), String> {
        let path = plugin_path(base_dir);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        backup_before_write(&path).map_err(|e| e.to_string())?;
        std::fs::write(&path, plugin_source(binary_path)).map_err(|e| e.to_string())
    }

    fn uninstall(&self, base_dir: &Path) -> Result<(), String> {
        let path = plugin_path(base_dir);
        if let Ok(text) = std::fs::read_to_string(&path) {
            if text.contains(MARKER) {
                backup_before_write(&path).map_err(|e| e.to_string())?;
                std::fs::remove_file(&path).map_err(|e| e.to_string())?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn plugin_path(base: &std::path::Path) -> std::path::PathBuf {
        base.join("plugin").join("harness-notify.js")
    }

    #[test]
    fn install_writes_a_plugin_file_using_the_event_hook_key() {
        let dir = tempdir().unwrap();
        let adapter = OpencodeAdapter;
        adapter.install(dir.path(), std::path::Path::new("/bin/harness-notify")).unwrap();
        let text = std::fs::read_to_string(plugin_path(dir.path())).unwrap();
        assert!(text.contains("event:"));
        assert!(text.contains("session.idle"));
        assert!(text.contains("permission.asked"));
        assert!(text.contains(r#"event.type === "session.created""#), "must use session.created as an event.type comparison inside the event: dispatcher");
        assert!(!text.contains("'session.created':"), "must not use session.created as a non-firing hooks object key");
    }

    #[test]
    fn install_is_idempotent() {
        let dir = tempdir().unwrap();
        let adapter = OpencodeAdapter;
        let bin = std::path::Path::new("/bin/harness-notify");
        adapter.install(dir.path(), bin).unwrap();
        let first = std::fs::read_to_string(plugin_path(dir.path())).unwrap();
        adapter.install(dir.path(), bin).unwrap();
        let second = std::fs::read_to_string(plugin_path(dir.path())).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn uninstall_removes_only_our_generated_file() {
        let dir = tempdir().unwrap();
        let adapter = OpencodeAdapter;
        adapter.install(dir.path(), std::path::Path::new("/bin/harness-notify")).unwrap();
        adapter.uninstall(dir.path()).unwrap();
        assert!(!plugin_path(dir.path()).exists());
    }

    #[test]
    fn uninstall_is_idempotent() {
        let dir = tempdir().unwrap();
        let adapter = OpencodeAdapter;
        let bin = std::path::Path::new("/bin/harness-notify");
        adapter.install(dir.path(), bin).unwrap();
        adapter.uninstall(dir.path()).unwrap();
        adapter.uninstall(dir.path()).unwrap();
        assert!(!plugin_path(dir.path()).exists());
    }

    #[test]
    fn uninstall_leaves_a_foreign_file_with_the_same_name_alone() {
        let dir = tempdir().unwrap();
        std::fs::create_dir_all(plugin_path(dir.path()).parent().unwrap()).unwrap();
        std::fs::write(plugin_path(dir.path()), "// hand-written, not ours").unwrap();
        let adapter = OpencodeAdapter;
        adapter.uninstall(dir.path()).unwrap();
        assert!(plugin_path(dir.path()).exists());
    }

    #[test]
    fn plugin_source_escapes_windows_backslashes_for_a_valid_js_string() {
        let bin = std::path::Path::new(r"C:\Users\jorge\.cargo\bin\harness-notify.exe");
        let text = plugin_source(bin);
        // Every backslash in the path must be doubled (valid JS escaping), never
        // dropped or turned into a control character like \b (backspace).
        assert!(text.contains(r#"spawn("C:\\Users\\jorge\\.cargo\\bin\\harness-notify.exe","#));
        assert!(!text.contains('\u{8}'), "must not contain a literal backspace control character");
    }
}
